/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.sql.Date;
import java.sql.Time;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Atracao;
import model.bean.Guia;
import model.bean.Reserva;
import model.bean.ReservaAtracao;
import model.bean.ReservaGuia;
import model.bean.Visitante;
import model.dao.AtracaoDAO;
import model.dao.GuiaDAO;
import model.dao.ReservaDAO;

/**
 *
 * @author acoli
 */
public class TelaPrincipalVisitante extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalVisitante
     */
    private Visitante visitanteLogado;
    private Reserva reservaSelecionada;
    
    public TelaPrincipalVisitante(Visitante v) {
        initComponents();
        this.visitanteLogado = v;
        this.setLocationRelativeTo(null);
        
        // Configurações iniciais
        preencherCombos();
        preencherTabela();
        
        // Título da janela com nome do usuário
        this.setTitle("Reserva - Visitante: " + v.getNomeVisitante());
    }
    
    public TelaPrincipalVisitante() {
        initComponents();
        preencherCombos();
        
    }
    
    private void preencherCombos() {
        cmbAtracao.removeAllItems();
        cmbGuia.removeAllItems();

        AtracaoDAO daoAtracao = new AtracaoDAO();
        for (Atracao a : daoAtracao.read()) {
            cmbAtracao.addItem(a);
        }

        GuiaDAO daoGuia = new GuiaDAO();
        for (Guia g : daoGuia.read()) {
            cmbGuia.addItem(g);
        }
    }
    
    private void preencherTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tblReserva.getModel();
        
        // 1. Configura as colunas na ordem que você quer
        modelo.setColumnIdentifiers(new Object[]{"ID", "Atração", "Data", "Hora", "Guia"});
        
        modelo.setNumRows(0);
        ReservaDAO dao = new ReservaDAO();
        
        // 2. Busca as reservas
        for (Reserva r : dao.read()) {
            // Filtra pelo visitante logado
            if (visitanteLogado != null && r.getVisitante() != null && 
                r.getVisitante().getIdVisitiante() == visitanteLogado.getIdVisitiante()) {
                
                // 3. Busca os nomes usando os métodos novos que criamos no DAO
                String nomeAtracao = dao.buscarNomeAtracao(r.getIdReserva());
                String nomeGuia = dao.buscarNomeGuia(r.getIdReserva());
                
                // 4. Adiciona na linha
                modelo.addRow(new Object[]{
                    r.getIdReserva(),
                    nomeAtracao,       // Agora mostra o nome (ex: Dinossauros)
                    r.getDataReserva(),
                    r.getHorario(),
                    nomeGuia           // Agora mostra o nome (ex: Carlos)
                });
            }
        }
    }
    
    private void limpar() {
        txtData.setText("");
        txtHora.setText("");
        cmbAtracao.setSelectedIndex(-1);
        cmbGuia.setSelectedIndex(-1);
        reservaSelecionada = null;
        btnCadastrar.setEnabled(true);
        btnEditar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbAtracao1 = new javax.swing.JComboBox<>();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        txtHora = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        cmbAtracao = new javax.swing.JComboBox();
        cmbGuia = new javax.swing.JComboBox();
        btnSair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReserva = new javax.swing.JTable();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(217, 181, 137));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nova reserva"));

        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });

        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(115, 80, 50));
        jLabel1.setText("Hora (hh:mm:ss)");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(115, 80, 50));
        jLabel2.setText("Data (aaaa-mm-dd)");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(115, 80, 50));
        jLabel3.setText("Guia");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(115, 80, 50));
        jLabel4.setText("Atração");

        btnCadastrar.setBackground(new java.awt.Color(115, 80, 50));
        btnCadastrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(217, 181, 137));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(115, 80, 50));
        btnLimpar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(217, 181, 137));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(115, 80, 50));
        btnExcluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(217, 181, 137));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(115, 80, 50));
        btnEditar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(217, 181, 137));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        cmbGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGuiaActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(115, 80, 50));
        btnSair.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSair.setForeground(new java.awt.Color(217, 181, 137));
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(btnSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtData)
                    .addComponent(cmbAtracao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHora)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCadastrar))
                            .addComponent(cmbGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(306, 306, 306))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbAtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnLimpar)
                    .addComponent(btnCadastrar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tblReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Atração", "Data", "Hora", "Guia"
            }
        ));
        tblReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReservaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblReserva);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            
            Reserva r = new Reserva();
            r.setDataReserva(Date.valueOf(txtData.getText())); // aaaa-mm-dd
            r.setHorario(Time.valueOf(txtHora.getText()));     // hh:mm:ss
            r.setVisitante(visitanteLogado);

       
            if (cmbAtracao.getSelectedItem() != null) {
                ReservaAtracao ra = new ReservaAtracao();
                ra.setReserva(r);
                ra.setAtracao((Atracao) cmbAtracao.getSelectedItem());
                ra.setHorarioVisita(r.getHorario());
                r.addAtracao(ra);
            }

            
            if (cmbGuia.getSelectedItem() != null) {
                ReservaGuia rg = new ReservaGuia();
                rg.setReserva(r);
                rg.setGuia((Guia) cmbGuia.getSelectedItem());
                r.addGuia(rg);
            }

            
            ReservaDAO dao = new ReservaDAO();
            if (dao.criarReservaCompleta(r)) {
                limpar();
                preencherTabela();
            }

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Data ou Hora inválida! \nUse: aaaa-mm-dd e hh:mm:ss");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (reservaSelecionada != null) {
            int confirmacao = JOptionPane.showConfirmDialog(this, "Deseja cancelar a reserva " + reservaSelecionada.getIdReserva() + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
            
            if (confirmacao == JOptionPane.YES_OPTION) {
                ReservaDAO dao = new ReservaDAO();
                dao.destroy(reservaSelecionada);
                limpar();
                preencherTabela();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma reserva na tabela para excluir.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(reservaSelecionada != null) {
             try {
                // 1. Pega Data e Hora
                reservaSelecionada.setDataReserva(Date.valueOf(txtData.getText()));
                reservaSelecionada.setHorario(Time.valueOf(txtHora.getText()));
                
                // 2. Pega a Atração do ComboBox
                if (cmbAtracao.getSelectedItem() != null) {
                    ReservaAtracao ra = new ReservaAtracao();
                    ra.setReserva(reservaSelecionada);
                    ra.setAtracao((Atracao) cmbAtracao.getSelectedItem());
                    ra.setHorarioVisita(reservaSelecionada.getHorario());
                    reservaSelecionada.getAtracoes().clear(); // Limpa lista antiga
                    reservaSelecionada.addAtracao(ra);        // Adiciona nova
                }

                // 3. Pega o Guia do ComboBox
                if (cmbGuia.getSelectedItem() != null) {
                    ReservaGuia rg = new ReservaGuia();
                    rg.setReserva(reservaSelecionada);
                    rg.setGuia((Guia) cmbGuia.getSelectedItem());
                    reservaSelecionada.getGuias().clear(); // Limpa lista antiga
                    reservaSelecionada.addGuia(rg);        // Adiciona novo
                }
                
                // 4. Manda pro DAO
                ReservaDAO dao = new ReservaDAO();
                if(dao.update(reservaSelecionada)) { // Usa o boolean pra saber se deu certo
                    limpar();
                    preencherTabela();
                }
                
             } catch (Exception e) {
                 JOptionPane.showMessageDialog(null, "Erro ao editar. Verifique os dados.");
                 e.printStackTrace();
             }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma reserva para editar.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tblReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReservaMouseClicked
        int linha = tblReserva.getSelectedRow();
        if (linha != -1) {
            // Pega dados da tabela
            int id = Integer.parseInt(tblReserva.getValueAt(linha, 0).toString());
            String nomeAtracaoTabela = tblReserva.getValueAt(linha, 1).toString(); // Coluna 1 = Atração
            String data = tblReserva.getValueAt(linha, 2).toString();
            String hora = tblReserva.getValueAt(linha, 3).toString();
            String nomeGuiaTabela = tblReserva.getValueAt(linha, 4).toString();    // Coluna 4 = Guia
            
            // Preenche Data e Hora
            txtData.setText(data);
            txtHora.setText(hora);
            
            // SELECIIONA A ATRAÇÃO NO COMBOBOX (Varre a lista até achar o nome igual)
            for (int i = 0; i < cmbAtracao.getItemCount(); i++) {
                Atracao a = (Atracao) cmbAtracao.getItemAt(i);
                if (a.getNomeAtracao().equals(nomeAtracaoTabela)) {
                    cmbAtracao.setSelectedIndex(i);
                    break;
                }
            }

            // SELECIONA O GUIA NO COMBOBOX
            for (int i = 0; i < cmbGuia.getItemCount(); i++) {
                Guia g = (Guia) cmbGuia.getItemAt(i);
                if (g.getNomeGuia().equals(nomeGuiaTabela)) {
                    cmbGuia.setSelectedIndex(i);
                    break;
                }
            }
            
            // Prepara objeto para edição
            reservaSelecionada = new Reserva();
            reservaSelecionada.setIdReserva(id);
            // Nota: Não precisamos setar o resto aqui pois vamos pegar dos campos na hora de salvar
            
            btnCadastrar.setEnabled(false);
            btnEditar.setEnabled(true);
        }
    }//GEN-LAST:event_tblReservaMouseClicked

    private void cmbGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGuiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGuiaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalVisitante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox cmbAtracao;
    private javax.swing.JComboBox<Admin> cmbAtracao1;
    private javax.swing.JComboBox cmbGuia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblReserva;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables

    private static class Admin {

        public Admin() {
        }
    }

    
}
